<header>
</header>
<section>
	<table>
		<tr>
			<td>
				<strong>Autor:</strong>
			</td>
			<td>
				<?= $obsah['autor'] ?>
			</td>
		</tr>
		<tr>
			<td>
				<strong>Vydáno:</strong>
			</td>
			<td>
				<?= $obsah['vydani'] ?>
			</td>
		</tr>
		<tr>
			<td>
				<strong>Kde leží:</strong>
			</td>
			<td>
				<?= $obsah['poloha'] ?>
			</td>
		</tr>
		<tr>
			<td>
				<strong>Poznámka:</strong>
			</td>
			<td>
				<?= $obsah['poznamka'] ?>
			</td>
		</tr>
	</table>

</section>
