<!DOCTYPE html>
<html lang="cs-cz">
<head>
	<base href="/localhost">
	<meta charset="UTF-8">
	<title><?= $titulek ?></title>
	<meta name="viewport" content="width=device-width">
	<meta name="description" content="<?= $popis ?>">
	<meta name="keywords" content="<?= $klicova_slova ?>">
	<meta name="author" content="Petr154">
	<link rel="stylesheet" href="../css/style.css">
	<link rel="shortcut icon" href="img/favicon.ico">
</head>
<body>
		<div class="wrapper">
			<div class="top-container">
			<h1 class="logo">Domácí knihovna</h1>
			<nav class="main-nav">
				<ul>
					<li><a href="clanek/uvod">Úvod</a></li>
					<li><a href="clanek">Články</a></li>
                    <li><a href="kniha">Knihy</a></li>
					<li><a href="kontakt">Kontakt</a></li>
				</ul>
			</nav>
		</div>

		<section class="search-container">
<!--
			<h1 class="search-text">Vyhledej článek</h1>
-->
			<div class="search-form">
				<form>
					<input type="text" placeholder="Hledejte v knihách...">
					<button type="submit" class="btn1">VYHLEDAT</button>
				</form>
			</div>
		</section>

		<section class="articles">
			<div class="box-container">
				<h3><?= $titulek ?></h3>
				<?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony ?>
			</div>

			<div class="login">
				<h3>Přihlášení</h3>
				<form>
					<div>
						<label>Jméno:</label><br>
						<input type="text" placeholder="Jméno..." required>
					</div>
					<div>
						<label>Heslo:</label><br>
						<input type="password" placeholder="Heslo..." required>
					</div>
					<button class="btn1" type="submit">Přihlásit</button>
				</form>
			</div>
		</section>
		<footer>
			<p>Petr154, Copyright &copy; 2019; inspirováno <a href="http://www.ITnetwork.cz" target="_blank">ITnetwork.cz</a>.</p>
		</footer>
	</div>
</body>
</html>
